### ISSUE TITLE
Game won't start with DXVK enabled. Could not initialize Graphics Device.

### ISSUE THREAD

**Issue by oopjot** [kyechou/leagueoflegends#72] opened 2022-12-17 21:11 UTC
### System information

 - Distro:  Arch
 - DE/WM: i3
 - CPU: Intel i5-4440
 - GPU: GeForce GTX 750 Ti (Kepler) 
 - Graphics card drivers installed: `nvidia-470xx-dkms`

If your issue is related to graphics display, please attach the output of `vulkaninfo --summary`.
```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.235


Instance Extensions: count = 19
-------------------------------
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 9
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 5
--------------------------
VK_LAYER_NV_optimus               NVIDIA Optimus layer         1.2.175  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.3.207  version 1

Devices:
========
GPU0:
        apiVersion         = 4202671 (1.2.175)
        driverVersion      = 1973960896 (0x75a840c0)
        vendorID           = 0x10de
        deviceID           = 0x1380
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = NVIDIA GeForce GTX 750 Ti
        driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
        driverName         = NVIDIA
        driverInfo         = 470.161.03
        conformanceVersion = 1.2.6.0
        deviceUUID         = e0445d12-8a34-4890-3b9f-42384664f16f
        driverUUID         = 21235eef-a066-1931-6351-fce5f4c8e266
```

### Describe the issue

Game works fine without DXVK enabled, but the performance is quite poor. When DXVK is enabled it crashes after champion select with `Could not initialize Graphics Device` popup. `vkcube` works just fine...

### Screenshots
![image](https://user-images.githubusercontent.com/71288625/208266084-3b6d1de6-c5c1-45d8-980b-860e8a4a5454.png)

Please let me know if I should provide any more outputs. I don't see anything suspicous running `leagueoflegends start` in verbose mode.
Thanks in advance!

**Comment by rurigk** [comment] 2023-02-08 04:38
Please read this https://github.com/doitsujin/dxvk/wiki/Driver-support

> Note: Nvidia's Kepler architecture (most GTX 600 / 700 series) is no longer supported. Please use DXVK 1.10.3 in combination with these cards.

Maybe this is your problem

**Comment by kyechou** [comment] 2023-02-08 05:13
@rurigk: Thanks for the information!

@oopjot: If the issue is indeed as described, you may try out DXVK 1.10.3 by changing this line in the script to `DXVK_VERSION=1.10.3`.
https://github.com/kyechou/leagueoflegends/blob/bd681ad02a9d25ea9840c3ba9e2621aba8202cc4/leagueoflegends#L345
And then run:
```sh
leagueoflegends rm-dxvk-cache
leagueoflegends del-dxvk
leagueoflegends add-dxvk
```

Or alternatively just reinstall the whole thing:
```sh
leagueoflegends reinstall
```

**Comment by kyechou** [comment] 2023-02-08 05:16
This doesn't seem like an issue of this project, so closing for now. Please feel free to open new issues for feature requests if deemed necessary.

**Closed by kyechou** 2023-02-08 05:16 UTC
Labels: support, graphics

**Comment by oopjot** [comment] 2023-02-24 14:03
It worked
@rurigk thank you very much
@kyechou thank you sir
