### ISSUE TITLE
Crash after champ select

### ISSUE THREAD

**Issue by DanProj** [kyechou/leagueoflegends#88] opened 2023-04-05 18:51 UTC
### System information

 - Distro: Pop!_OS 22.04
 - DE/WM/Compositor: Gnome 42.5
 - CPU: Intel i7-8700
 - GPU: Nvidia GeForce RTX 3070
 - Graphics card drivers installed: nvidia 525.89.02

Unsure if the issue is graphics related, [vulkaninfo](https://pastebin.com/ZkLtvEzu)

### Describe the issue

Can load into the client but once I try to get past champion select the game crashes.

### Steps to reproduce

[Verbose output](https://pastebin.com/Bw09DWB9)
Note: I am using [noah1510's wrapper](https://github.com/noah1510/lol-linux-12.7) for leagueoflegends because of my distro.

1. `./lol.sh -v start`
2. Start a practice match and proceed to champ select
3. Notice crash when attempting to launch the game

### Screenshots

![image](https://user-images.githubusercontent.com/81483632/230175319-34147fdb-41ec-4d8c-99ab-794ca52e7445.png)

**Comment by PalanixYT** [comment] 2023-04-05 18:52
duplicate of #83

**Comment by kyechou** [comment] 2023-04-05 18:53
Duplicate #83.

**Closed by kyechou** 2023-04-05 18:53 UTC
Labels: duplicate
