### ISSUE TITLE
Stuck/frozen once in game

### ISSUE THREAD

**Issue by Abdulee** [kyechou/leagueoflegends#50] opened 2022-06-15 19:37 UTC
- Distro: Arch Linux
 - DE/WM: Gnome
 - CPU: i7 8750h
 - GPU: GTX 1060
 - Graphics card drivers installed:  `mesa`, `nvidia-prime`, `nvidia`

### Describe the issue

Once in a game the game completely gets stuck(sometimes as soon as it starts other times after 2-3 minutes in rift) and it seems as if the gpu has crashed or something. I can move the cursor but thats it nothing else. No keystrokes respond and game is completely frozen. Can't alt tab or anything else. Keep in mind basically the entire system gets stuck(except that I can move mouse I guess)

### Steps to reproduce

1. open terminal and run prime-run leagueoflegends start
2. wait, when the riot login comes up login with credentials
3. wait(2-5mins). Start a lobby get in a practice or normal game.
4. stuck!

I have looked at troubleshooting section in leagueoflinux reddit but that looks like instructions for lutris mainly. You help is appreciated thanks.

**Comment by rurigk** [comment] 2022-07-01 02:43
I'm having a similar issue, between minute 2-5 the game freezes for some seconds

Distro: Manjaro
DE/WM: KDE
CPU: Ryzen 7 2700X
GPU: RX 6700XT
Graphics card drivers installed: `mesa`, `RADV`

**Comment by kyechou** [comment] 2022-08-17 14:21
Hi @Abdulee, @rurigk, please try again with the latest version, now that wine-lol had been updated with GE patches, and then clean-reinstall the game. If the issue persists, please provide the output of `pacman -Qi leagueoflegends-git' and the screenshot of the "Graphics" tab when you run `leagueoflegends run winecfg`.

**Comment by rurigk** [comment] 2022-08-17 16:47
I already try the lastest
It's not a problem anymore, but now I have to kill the game process after every match or the client keeps frozen

**Comment by kyechou** [comment] 2022-08-17 17:34
Yeah, it seems to be caused by the 7.14 patch set.  #57 is the main thread for that issue, where one workaround might be revert wine GE to 7.0.4, but I haven't tested it.  Closing this for now.

**Closed by kyechou** 2022-08-17 17:34 UTC
Labels: bug, support, graphics
