### ISSUE TITLE
League Client crashes after fresh install 

### ISSUE THREAD

**Issue by rizakar** [kyechou/leagueoflegends#85] opened 2023-04-05 13:21 UTC
### System information

 - Distro: EndeavourOS
 - DE/WM/Compositor: Cinnamon
 - CPU: AMD Ryzen 7 5800HS
 - GPU: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] 
 - Graphics card drivers installed: nvidia

### Describe the issue

League Client does not launch. After Riot Client opens `RiotClientUxRender.exe` crashes (even while downloading the game, but the installation completes anyway).

### Steps to reproduce

1. Install `leagueoflegends-git` package from AUR.
2. Install League of Legends via `leagueoflegends install` script.
3. Close Riot Client.
4. Run `leagueoflegends start`

[Here's the log](https://gist.github.com/rizakar/6238d21b976ae817b9cf30e8f44cc45d)

EDIT: added the full log after running `leagueoflegends -v start`

### Screenshots

![Screenshot from 2023-04-05 10-04-04](https://user-images.githubusercontent.com/94943542/230088996-2190bff0-6946-4173-902f-9552f5824321.png)

**Comment by Laci0503** [comment] 2023-04-05 15:56
You were right, I forgot to update the script to use wine-lol (it's not in the default location for me). Now i get through the install fine, but i seem to get the same crash when entering a game as with the lutris install.
I've tried with both the wine-lol runner installed with lutris, and downloading manually.
It shows the same error reporting window as seen the other issue describing crash after champion select. I will post further news in there.
Last few lines of the log:
```
LAYER | DEBUG: Unloading layer library libVkLayer_MESA_device_select.so
LAYER | DEBUG: Unloading layer library libVkLayer_MESA_device_select.so
0a04:err:module:open_builtin_so_file failed to load .so lib "/home/laci0503/lutris-ge-lol-7.0-5-x86_64/lib/wine/i386-unix/d3d12.dll.so"
0518:err:seh:dispatch_exception unknown exception (code=c0000420) raised
```

**Comment by foxyllakora** [comment] 2023-04-05 16:34
Here is the error I'm getting when the game tries to load in after champ select:

02f0:err:seh:dispatch_exception unknown exception (code=c0000420) raised

That's the only error that shows up using `leagueoflegends -v start`

OS: EndeavourOS
CPU: Ryzen 9 5950x
GPU: AMD XFX 6950XT
Mobo: ASUS TUF Gaming X570-Plus
Ram: G.Skill DDR4 32GB

**Comment by kyechou** [comment] 2023-04-05 18:21
Hi @Laci0503, that's good to know! So it's the same problem as #83. The SEH unknown exception is the problem. The line `err:module:open_builtin_so_file failed to load .so lib "/home/laci0503/lutris-ge-lol-7.0-5-x86_64/lib/wine/i386-unix/d3d12.dll.so"` should be a minor issue caused by build/install-time errors and can be fixed relatively easily by having a proper installation. noah1510 created a [script](https://github.com/noah1510/lol-linux-12.7) for setting up wine-lol in non-Arch distros. Maybe that'd help. In the future I may work on having packages for each popular distribution too, if I have time.

Closing now. Duplicate #83.

**Comment by helena-dev** [comment] 2023-04-05 19:00
> Hi @Laci0503, from your log it seems you're not using wine-lol. LoL won't work with the mainline wine.
> 
> @rizakar, please make sure that you're running wine-lol instead of regular wine? How did you install wine-lol and where is the installation path? Please share the output of `leagueoflegends run which wine`.

Hi. I'm having the same problem as @rizakar. `leagueoflegends run which wine` outputs `/opt/wine-lol/bin/wine`. The game installs fine and the Riot client works. But I can't enter into the League client after log in.

**Comment by rizakar** [comment] 2023-04-06 00:17
@kyechou thanks a lot for replying, I do have `wine-lol` installed (`wine-lol-bin` precisely), in fact, I used it with vulkan through lutris until this patch.

Here's the output of both commands + one extra command about `wine-lol`:

```
$  leagueoflegends run which wine
/opt/wine-lol/bin/wine
```

```
$ pacman -Qi leagueoflegends-git
Name            : leagueoflegends-git
Version         : 13.7.1.r0.gfb60c87-1
Description     : League of Legends helper script
Architecture    : any
URL             : https://github.com/kyechou/leagueoflegends
Licenses        : GPL3
Groups          : None
Provides        : leagueoflegends
Depends On      : wine-lol  winetricks  bash  curl  openssl  samba  mesa-utils
                  gnutls  lib32-gnutls  libldap  lib32-libldap  openal
                  lib32-openal  libpulse  lib32-libpulse  alsa-lib
                  lib32-alsa-lib  mpg123  lib32-mpg123  unixodbc
                  lib32-unixodbc  vkd3d  lib32-vkd3d  vulkan-icd-loader
                  lib32-vulkan-icd-loader  vulkan-driver  lib32-vulkan-driver
Optional Deps   : amdvlk: AMD Vulkan driver
                  nvidia-utils: NVIDIA Vulkan driver [installed]
                  vulkan-intel: Intel's Vulkan mesa driver
                  vulkan-radeon: Radeon's Vulkan mesa driver
                  lib32-amdvlk: AMD Vulkan driver (32-bit)
                  lib32-nvidia-utils: NVIDIA Vulkan driver (32-bit) [installed]
                  lib32-vulkan-intel: Intel's Vulkan mesa driver (32-bit)
                  lib32-vulkan-radeon: Radeon's Vulkan mesa driver (32-bit)
Required By     : None
Optional For    : None
Conflicts With  : leagueoflegends
Replaces        : None
Installed Size  : 132.35 KiB
Packager        : Unknown Packager
Build Date      : 2023-04-05T09:19:42 -03
Install Date    : 2023-04-05T09:19:45 -03
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

```
$ pacman -Qi wine-lol                                                                                                                                                                1
Name            : wine-lol-bin
Version         : 1:7.0_5-1
Description     : A compatibility layer for running Windows programs - GloriousEggroll custom wine build for running League of Legends
Architecture    : x86_64
URL             : https://github.com/GloriousEggroll/wine-ge-custom
Licenses        : LGPL
Groups          : None
Provides        : wine-lol
Depends On      : attr  lib32-attr  fontconfig  lib32-fontconfig  lcms2  lib32-lcms2  libxml2  lib32-libxml2  libxcursor  lib32-libxcursor  libxrandr  lib32-libxrandr  libxdamage
                  lib32-libxdamage  libxi  lib32-libxi  gettext  lib32-gettext  freetype2  lib32-freetype2  glu  lib32-glu  libsm  lib32-libsm  gcc-libs  lib32-gcc-libs  libpcap
                  lib32-libpcap  faudio  lib32-faudio  desktop-file-utils
Optional Deps   : giflib [installed]
                  lib32-giflib [installed]
                  libpng [installed]
                  lib32-libpng [installed]
                  libldap [installed]
                  lib32-libldap [installed]
                  gnutls [installed]
                  lib32-gnutls [installed]
                  mpg123 [installed]
                  lib32-mpg123 [installed]
                  openal [installed]
                  lib32-openal [installed]
                  v4l-utils [installed]
                  lib32-v4l-utils [installed]
                  libpulse [installed]
                  lib32-libpulse [installed]
                  alsa-plugins [installed]
                  lib32-alsa-plugins [installed]
                  alsa-lib [installed]
                  lib32-alsa-lib [installed]
                  libjpeg-turbo [installed]
                  lib32-libjpeg-turbo [installed]
                  libxcomposite [installed]
                  lib32-libxcomposite [installed]
                  libxinerama [installed]
                  lib32-libxinerama [installed]
                  opencl-icd-loader [installed]
                  lib32-opencl-icd-loader [installed]
                  libxslt [installed]
                  lib32-libxslt [installed]
                  libva [installed]
                  lib32-libva [installed]
                  gtk3 [installed]
                  lib32-gtk3 [installed]
                  gst-plugins-base-libs [installed]
                  lib32-gst-plugins-base-libs [installed]
                  vulkan-icd-loader [installed]
                  lib32-vulkan-icd-loader [installed]
                  sdl2 [installed]
                  lib32-sdl2 [installed]
                  vkd3d [installed]
                  lib32-vkd3d [installed]
                  sane
                  libgphoto2 [installed]
                  gsm [installed]
                  ffmpeg [installed]
                  cups [installed]
                  samba [installed]
                  dosbox [installed]
Required By     : leagueoflegends-git
Optional For    : None
Conflicts With  : wine-lol
Replaces        : None
Installed Size  : 560.54 MiB
Packager        : Unknown Packager
Build Date      : 2022-11-06T20:18:49 -03
Install Date    : 2022-11-06T20:22:38 -03
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**Comment by fattyre** [comment] 2023-04-06 00:42
Identical issue for me on Endeavour with a 3060 Mobile

**Comment by rizakar** [comment] 2023-04-07 01:27
Hey @fattyre I have resolved this!

The issue is that for some reason our default GPU is the integrated GPU instead of the NVIDIA card. I found this by running `glxinfo -B`, and it outputs my integrated AMD GPU info, but nothing about the NVIDIA card.

So I tried installing the Vulkan drivers for Radeon and it worked! So then I investigated further, and installed NVIDIA Prime and by running the League script with it, it actually detects my NVIDIA card!

So here's what you need to do:
1. Install `nvidia-prime` package.
2. Run League:  `prime-run leagueoflegends start`

Now, I still can't run get into a game, because of the critical error that is affecting everyone. But at least is some progress for us :stuck_out_tongue:

**Comment by kyechou** [comment] 2023-04-07 01:54
Cool, sounds like it's resolved then! Unfortunately there doesn't seem to be much I can do for the matter in the launch script since the users should be able to decide for themselves which GPU/driver to use.

**Closed by kyechou** 2023-04-07 01:54 UTC
Labels: question, support, graphics
