### ISSUE TITLE
Leauge of Legends logo shows and then it crashes

### ISSUE THREAD

**Issue by JakubChorzepa** [kyechou/leagueoflegends#17] opened 2021-09-21 15:53 UTC
It is leagueoflegends -v start output
```
> + shift
> + :
> + case "${1-}" in
> + break
> + case "${1-}" in
> + start_LoL
> + '[' '!' -f '/home/jakub/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe' ']'
> + port_waiting_daemon
> + process=LeagueClientUx.exe
> + msg Starting...
> + echo -e '[+] Starting...'
> [+] Starting...
> + loading_screen
> + '[' 1 -eq 1 ']'
> + zenity --progress --pulsate --auto-close --no-cancel '--title=League of Legends' --window-icon=/usr/share/icons/hicolor/256x256/apps/leagueoflegends.png '--text=Waiting for the League client port to open...'
> ++ timeout 2m sh -c 'until ps -C LeagueClientUx.exe -o pid=; do sleep 1; done | sed '\''s/[[:space:]]*//g'\'''
> ++ winepath -w '/home/jakub/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe'
> ++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
> + WIN_CLIENT_EXE='C:\Riot Games\Riot Client\RiotClientServices.exe'
> + wine 'C:\Riot Games\Riot Client\RiotClientServices.exe' --launch-product=league_of_legends --launch-patchline=live
> + uxpid=
> + wineserver --wait
> + wait
```

**Comment by kyechou** [comment] 2021-11-10 22:36
The game works fine on my end, and I was unable to reproduce the issue. Could you please provide the detailed information of your setup?

**Comment by kyechou** [comment] 2021-11-11 07:07
Closing for duplication (#16). Please feel free to open a new issue if there's more specific information.

**Closed by kyechou** 2021-11-11 07:07 UTC
